/* Generated by Together */

package docs.future.doe;

/**
 * @stereotype abstractfactory
 */
public class DoeManager {
    public Thing getThing(String name) {
        return null;
    }

    public Person getPerson(String name) {
        return null;
    }

    public Place getPlace(String name) {
        return null;
    }

    public Item getItem(String name) {
        return null;
    }
}
