
/**
 * This is autogenerated code created by config-test.xsl stylesheet run against config.xml.
 * It should generally be altered by editing config.xml or (less often) by editing
 * config-test.xsl.
 * It is stored in CVS purely on the principle that users ought to be able to compile
 * without needed all the code-generation tools.
 * @see ../../etc/config-test.xsl
 * @see ../../resource/config.xml
 * @author Joe Walker [joe at eireneh dot com]
 */
public class ConfigTest
{
    public static void main(String[] args) throws Exception
    {
        String stemp = "";
        String[] astemp = new String[0];
        boolean btemp = false;
        Class ctemp = null;
        int itemp = 0;
        
        stemp = org.crosswire.jsword.book.Bibles.getDefaultByName();
        org.crosswire.jsword.book.Bibles.setDefaultByName(stemp);
  
        btemp = org.crosswire.jsword.book.raw.RawBible.isDefaultCacheData();
        org.crosswire.jsword.book.raw.RawBible.setDefaultCacheData(btemp);
  
        stemp = org.crosswire.jsword.book.sword.SwordBibleDriver.getSwordDir();
        org.crosswire.jsword.book.sword.SwordBibleDriver.setSwordDir(stemp);
  
        astemp = org.crosswire.jsword.book.remote.HttpRemoteBibleDriver.getURLs();
        org.crosswire.jsword.book.remote.HttpRemoteBibleDriver.setURLs(astemp);
  
        btemp = org.crosswire.jsword.passage.PassageUtil.isPersistentNaming();
        org.crosswire.jsword.passage.PassageUtil.setPersistentNaming(btemp);
  
        itemp = org.crosswire.jsword.passage.PassageUtil.getBlurRestriction();
        org.crosswire.jsword.passage.PassageUtil.setBlurRestriction(itemp);
  
        itemp = org.crosswire.jsword.passage.Books.getCase();
        org.crosswire.jsword.passage.Books.setCase(itemp);
  
        ctemp = org.crosswire.common.swing.LookAndFeelUtil.getLookAndFeel();
        org.crosswire.common.swing.LookAndFeelUtil.setLookAndFeel(ctemp);
  
        btemp = org.crosswire.common.swing.ExceptionPane.isHelpDeskListener();
        org.crosswire.common.swing.ExceptionPane.setHelpDeskListener(btemp);
  
        btemp = org.crosswire.common.swing.ExceptionShelf.isHelpDeskListener();
        org.crosswire.common.swing.ExceptionShelf.setHelpDeskListener(btemp);
  
        astemp = org.crosswire.common.swing.DetailedExceptionPane.getSourcePath();
        org.crosswire.common.swing.DetailedExceptionPane.setSourcePath(astemp);
  
    }
}
  